vue/components/pickers/pickers.vue
With the new iOS 13.1 there seems to have been some kind of breaking change that makes the `overflow: hidden` in the swatches not work when there is scrolling in its container.
Somehow it seems that [setting the z-index fixes the issue](https://gist.github.com/adamcbrewer/5859738#gistcomment-2008691).
Before:
After:
Another option would be to [add](https://gist.github.com/ayamflow/b602ab436ac9f05660d9c15190f4fd7b) `-webkit-mask-image: -webkit-radial-gradient(white, black);`.
I could only reproduce this issue on iOS `13.1` using a real device or the MacOS simulator. Even with the same Safari and webkit versions (13.0.1 or 605.1.15) it wasn't reproducible in desktop.
=> Hack for fixing overflow in iOS 13.1

vue/components/configurator.vue
| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/ripe-commons-pluginus/issues/XXX |
| Decisions | Improve loader component hide timing to be closer to the rendering of the first image. |
=> Improve loader component hide timing

vue/components/personalization.vue
| - | - |
| --- | --- |
| Issue | - |
| Decisions | Personalization was disabled by default, forcing plugin implementations to explicitly trigger a `enable_personalization` event. This was just being done for Sergio Rossi, meaning that all other implementations would never have the personalization button enabled.  This was a [breaking change](https://github.com/ripe-tech/ripe-commons-pluginus/commit/0c2feb84fd2834cae7d423fd384dcb43b88d4747) motivated by not wanting the button to appear enabled when it's still loading, but with the current implementation, both scenarios seem to be accounted for.  |
| Animated GIF |   |
=> Enable personalization by default

vue/components/size_form/reference.vue
=> Add button size overflow

.storybook/config.js
| - | - |
| --- | --- |
| Decisions | All pluginus apps use a pluginus bus, not a Vue bus, therefore the storybook must reflect that. |
=> Use the correct bus in Storybook

vue/mixins/logic.js
Renamed `variant` since we usually use that as a prop for UI components (e.g. `dense`, etc). I've confirmed that this wasn't being used in neither in Retail nor White.
=> Rename variant in logic mixin

js/base/main.js
| - | - |
| --- | --- |
| Decisions | Expose a higher-level operation for changing the current model. While the existing `setModel` works, it would force clients to re-implement the resolving of the DKU, product ID, etc. This is provided as a global mixin rather than an event bus to allow `await`ing for it so that we can have loading or similar. |
=> Exposet set model options

js/base/main.js, js/util/url-changer.js, vue/store.js
| - | - |
| --- | --- |
| Decisions | Now that versions are a first-class citizen, particularly in RIPE White with the builds explorer, it should also be included in the URL. It was already possible to enter with a specific version in the URL, so it even makes more sense. |
=> Sync version to the URL

js/base/main.js, vue/components/organisms/pickers/pickers.vue
| - | - |
| --- | --- |
| Issue | Fixes https://github.com/ripe-tech/ripe-white/issues/313 |
| Decisions | We were completely ignoring how White sets the parts (`options.parts`) or the DKU (`options.dku`). Besides, `pickers` had to be adapted because for some reason when entering with the DKU the `post_config` event is triggered before the `choices`, even though they're being triggered in the correct order by the RIPE SDK's `update`, which means that it's not guaranteed that the available options (choices) are ready when a part becomes active (when a config changes)  |
=> #313: Fix init with parts and DKU

vue/filters/money.js
| - | - |
| --- | --- |
| Decisions | A call for `money(0, "USD")` is perfectly valid but would product `` rather than `$ 0.00` due to `0` being coerced to `false`. This fixes it. |
=> Fix money format for 0

vue/components/organisms/pickers/pickers.vue
| - | - |
| --- | --- |
| Issue | Fixes https://github.com/ripe-tech/ripe-retail/issues/234 |
| Decisions | Reverts the regression created in https://github.com/ripe-tech/ripe-commons-pluginus/commit/997b3aa42c735b7d9e6106fe407f3779bd14f4c3#diff-38c90b47b74305883cdb8712366f3538 by re-adding the deleted default slot, which RIPE Retail was using for injecting the personalization button.  |
=> #234: Fix regression by re-adding slot

vue/components/molecules/modal/modal.vue
| - | - |
| --- | --- |
| Issue | No issue created. But the issue is that on firefox the padding-bottom isn't being respected when a `overflow-y: auto` css is present in the code |
| Decisions | Passed the bottom padding to the latest child of `modal-footer` instead of is container `modal-container`. |
| Animated GIF |  Bug:</br><img width="1024" alt="Screenshot 2020-05-08 at 10 43 13" src="https://user-images.githubusercontent.com/13239857/81393750-c7781600-9118-11ea-9b51-9d7063a98cca.png"></br>Fix:<br><img width="1024" alt="Screenshot 2020-05-08 at 10 42 39" src="https://user-images.githubusercontent.com/13239857/81393956-16be4680-9119-11ea-91be-aa08563ed3dc.png"> |
| Dependencies | - |
=> Fix modal padding in firefox

js/base/main.js
| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/ripe-white/issues/448 |
| Decisions | Options that are not defined shouldn't cause a new SDK configuration request. The source of options, the Vuex store, has all kinds of ways to say something is undefined (null, empty string, undefined, ...) so the comparison can't be so strict. |
=> #448: Fix entering with product ID or DKU

vue/components/molecules/tabs/tab.vue
| - | - |
| --- | --- |
| Decisions | Makes the default be `{}` instead of `undefined`. |
=> Fix default prop

js/base/main.js, vue/components/molecules/restrictions-alert/restrictions-alert.vue
| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/ripe-white/issues/467 |
| Decisions | • Closing the restrictions alert when the `undo` event is triggered<br><br>• The approach to close the restrictions alert when an event related to a change in the customization is triggered wasn't followed because of the following order of events:<br>- Strass is selected<br>- Event `restrictions` is triggered (which makes the restrictions alert open)<br>- Event `part` is triggered (which would make the restrictions alert close)<br>So, given the order of the events, the restrictions alert will never open.<br><br>After discussing with @gcandal, we opted for this approach.|
| Animated GIF | **Before fix:**<br>![White-Restrictions_alert_doesnt_close_after_undo_bug](https:/ …
=> #467 Fixed restrictions alert not closing when undo button is clicked

bundles/config.en_us.json, js/index.js, js/ui/base-personalization/base-personalization.js, js/ui/base-personalization/base-personalization.vue, js/ui/base-personalization/index.js, js/ui/index.js, vue/components/forms/personalization-form/index.js, vue/components/forms/personalization-form/initials-images.vue, vue/components/forms/personalization-form/reference.vue
| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/ripe-white/issues/349 |
| Decisions | Changed `initials-images` to support updating when groups change. Support for one or multiple groups. It takes into account all the properties of a build (style, font, position) to apply the profiles. It takes into account the information in $alias regarding the viewport of `step::personalization` for the personalization modal images. Lastly, it uses the font and style properties to build and parse the engraving information. |
| Dependencies | • https://github.com/ripe-tech/ripe-sdk/pull/173 <br> • https://github.com/ripe-tech/ripe-white/pull/453 |
| Testing | • http://localhost:3000/?technical=1&brand=kirkwood&model=alligator_beya_loafer <br> • …
=> #349: Generic personalization plugin

vue/test/base.js, vue/test/components/restrictions-alert/restrictions-alert.test.js, vue/test/mocks/filters/index.js, vue/test/mocks/filters/locale.js, vue/test/mocks/index.js, vue/test/mocks/mixins/index.js
| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/ripe-commons-pluginus/issues/122 |
| Decisions | • Added the test "Closes on Undo" for the `restrictions-alert` component. The test goes as follows: <br>&nbsp;&nbsp;&nbsp;&nbsp;- Triggers event "restrictions" with changes to open the `restritions-alert` <br>&nbsp;&nbsp;&nbsp;&nbsp;- Triggers the event "undo" which will make the `restritions-alert` close<br>• Added the test "'Doesn't open when an "restrictions" event, with no changes, is triggered'" for the `restrictions-alert` component. The test goes as follows: <br>&nbsp;&nbsp;&nbsp;&nbsp;- Triggers event "restrictions" with no changes <br>&nbsp;&nbsp;&nbsp;&nbsp;- The `restritions-alert` shouldn't open after the event |
| Animated GIF | …
=> #122 Unit test for the restrictions-alert fix

vue/components/organisms/personalization/personalization.vue
| - | - |
| --- | --- |
| Issue | Related to #116  |
| Decisions |  Added v-if that prevents mounting the dynamic component if the form is null. This will be necessary for the generic-personalization unit tests. Without this, when mounting the personalization component, a an error `Error in render: "TypeError: Cannot read property 'template' of null" ` like this is shown, since the `form` is `null`. This does not change the behaviour of the component. |
| Animated GIF |  -- |
=> #116: Check if personalization's dynamic component is null

vue/components/forms/personalization-form/reference.vue
| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/ripe-white/issues/503 |
| Decisions | Add semantic classes to inputs for testing purposes. |
=> #503 Add semantic classes to generic personalization

vue/components/forms/personalization-form/reference.vue
| - | - |
| --- | --- |
| Decisions | Fixes a regression caused in https://github.com/ripe-tech/ripe-commons-pluginus/commit/9f48dfa20d74cf79431f781cf4e4000ffdc53536 where we lost the type of the select (eg `font`, `position`) in the name of the class. This is not being used in any test, so no adaptations need to be made. |
=> Fix generic plugin select class name

vue/components/forms/personalization-form/reference.vue
| - | - |
| --- | --- |
| Issue | Closes https://github.com/ripe-tech/ripe-white/issues/534 |
| Decisions | Computed `properties` isn't reactive as it doesn't know that the values for the keys weren't changed. To fix that we use the same approach as in pickers where we listen for the `locale_map_changed` and we refresh the component |
| Animated GIF | ![locales_in_initials_not_updating_fix](https://user-images.githubusercontent.com/22588915/88822106-62820880-d1bb-11ea-8a0e-cd66f6c6e802.gif)|
=> #534 Fixed initials locales not updating

vue/components/forms/personalization-form/reference.vue
| - | - |
| --- | --- |
| Decisions | The engraving-from-properties generation was wrong, as it was using a `propertyType:propertyValue` format, when it [should be the opposite](https://github.com/ripe-tech/ripe-core/blob/c10268ae18bed898a296f3fe7fb5bb1187ea5eca/src/ripe_core/test/controllers/web/adapter.py#L406). The image was still correctly generated because we were using a custom (and buggy) `parseEngraving` implementation. In practice, this changes nothing except that created orders will have a proper `engraving`. |
=> Fix engraving for generic personalization

.storybook/config.js, vue/components/molecules/index.js, vue/components/molecules/thumbnails-groups/index.js, vue/components/molecules/thumbnails-groups/thumbnails-groups.stories.js, vue/components/molecules/thumbnails-groups/thumbnails-groups.vue
| - | - |
| --- | --- |
| Decisions | Add a component that represents a set of thumbnails, where each one is a different initials group. This is equivalent to `thumbnails` but for groups instead of frames. |
| Issue | https://github.com/ripe-tech/ripe-white/issues/531 |
| Animated GIF | ![](http://g.recordit.co/kbvwHE4EnP.gif) |
=> Thumbnails groups component

js/base/main.js
| - | - |
| --- | --- |
| Issue | Related to https://github.com/ripe-tech/ripe-sdk/pull/205 |
| Decisions | Removed `.text()` from `runLogicP` call since that conversion is made by the `sdk`.  |
=> Remove .text() from runLogicP call

bundles/config.en_us.json, bundles/config.ja_jp.json, bundles/config.zh_cn.json, vue/components/forms/personalization-form/reference.vue
| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/ripe-white/issues/664 |
| Dependencies | https://github.com/ripe-tech/ripe-commons-pluginus/pull/172 |
| Decisions | Add missing translation keys and change every filter `locale` to the new computed method `locale`. |
=> #664 Add missing personalization locale keys

bundles/config.en_us.json, bundles/config.ja_jp.json, bundles/config.zh_cn.json, vue/components/forms/personalization-form/reference.vue
| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/ripe-white/issues/664 |
| Decisions | Add missing tab properties to appear on tab message. Those will be matched with chosen model properties and translated accordingly if they exist, otherwise. |
=> #644 Add missing tab properties

vue/store.js
| - | - |
| --- | --- |
| Issue | Detected when working in https://github.com/ripe-tech/ripe-retail-vendors/pull/72, where the lack of it would lead to weird behavior because of a shared variable between unrelated components. |
=> Object.assign before saving to store

vue/components/organisms/configurator/configurator.vue
| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/ripe-white/issues/351 |
| Decisions | Added `onError` prop that is called when an error with the `changeFrame()` method occurs |
=> #351 Prop onError

vue/components/forms/personalization-form/reference.vue
| - | - |
| --- | --- |
| Issue | Asked by @joamag  |
| Decisions | Hide the label for `main` or when there is a single group. |
| Animated GIF | ![image](https://user-images.githubusercontent.com/3048875/100474785-552d4a00-30d9-11eb-8eba-eecaca12a764.png) |
=> Hide group label when there is a single group

js/base/main.js, vue/store.js
| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/ripe-commons-pluginus/pull/175#pullrequestreview-532307550 |
| Decisions | Do it only when the model has personalization. Allows being called from any point in the application but currently, that's not needed. |
=> refreshInitialsData only when needed

vue/components/organisms/personalization/personalization.vue
| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/ripe-white/issues/698 |
| Decisions | Reset valid state when config changes - `pre_config`. |
| Animated GIF | ![Peek 2020-11-27 18-03](https://user-images.githubusercontent.com/24736423/100475848-07fea780-30dc-11eb-8fef-0af748f46b9a.gif) |
=> #698 Add validation reset on pre_config

vue/components/organisms/size/size.vue, vue/store.js
| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/ripe-white/issues/678#issuecomment-737867348 |
| Decisions | Because there are multiple places where the size modal can be opened, the activation of the size plugin should be globally accessible. |
=> Store size active

vue/components/organisms/pickers/pickers.vue
| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/ripe-white/issues/673 |
| Decisions | Applying the same centering logic of the color pickers to parts and materials. There were experiments made with other logic, such as using the `offsetLeft` of the element to calculate the `scrollLeft`, but it ended up being way more complicated than the final solution. <br> The `centerActiveColor` function was not refactored to use the new function `centerElement` because it contains specific logic inside the scroll incrementing loop. |
| Animated GIF | ![pickers-scroll-center](https://user-images.githubusercontent.com/25725586/100126301-b05f0280-2e75-11eb-95c5-524ec183d7ff.gif)![scroll-parts-center](https://user-images.githubusercontent.com/25725586/100126329-b94fd400 …
=> #673: Centering scroll logic applied to parts+materials

vue/components/organisms/pickers/pickers.vue
| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/ripe-white/issues/689 |
| Decisions | Add translateZ to swatch picker as suggested in https://github.com/ripe-tech/ripe-white/issues/689#issuecomment-732071519 |
=> #689 Fix square swatches for webkit

vue/components/organisms/personalization/personalization.vue, vue/mixins/logic.js
| - | - |
| --- | --- |
| Issues | https://github.com/ripe-tech/ripe-retail-vendors/issues/97 <br/> https://github.com/ripe-tech/ripe-white/issues/714 |
| Decisions | Use the existing sanitization so that it can cope with plugins that send an invalid state (having engraving without initials). |
=> Fix engraving without initials

vue/store.js
| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/builds-static/issues/903 <br/> https://github.com/ripe-tech/ripe-retail-vendors/issues/104 |
| Decisions | Use a more fine-grained error handling, to tolerate partial information retrieval when there is an error calling one of the methods. |
=> Fine-grained error handling of 'runLogic'

.storybook/preview.js
| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/ripe-components-vue/pull/420#issuecomment-757757548 |
| Decisions | Fixed storybook width thus removing the always present scrollbar.<br><br>This issue ocurred because in storybook 6.0 there was an added `padding `of `1rem`. To fix this we needed to add the `fullscreen` param in  `.storybook/preview.js`. (See https://storybook.js.org/docs/vue/configure/story-layout). For more information about this problem, check [this github issue](https://github.com/storybookjs/storybook/issues/12109). |
| Animated GIF | **Before fix:**<br>![storybook_before](https://user-images.githubusercontent.com/22588915/103999777-3d93b780-5195-11eb-8785-5dbbe5bd6ac2.gif)<br><br>**After …
=> Fixed storybook not being in fullscreen

vue/components/organisms/pickers/pickers.vue
| - | - |
| --- | --- |
| Issue | Resizing the window with `features=~pickers` causes errors |
=> fix: tolerate pickers disappearing

vue/plugins/locale.js
| - | - |
| --- | --- |
| Issue | Changing the locale map is not reactive, making its population highly dependent on the order on which locale changes are done. |
=> fix: react to locale map changes

vue/plugins/locale.js
| - | - |
| --- | --- |
| Issue | Locales were not reactive once again after https://github.com/ripe-tech/ripe-commons-pluginus/pull/209 due to https://github.com/ripe-tech/ripe-commons-pluginus/commit/007543865c179e911fa071cf6b5e11296a9a1224. This was because the same object was assigned in both instances. |
=> fix: fix locale reactivity by using a defensive copy

vue/components/organisms/pickers/pickers.vue
| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/ripe-white/issues/673#issuecomment-762817148 |
| Decisions | Two fixes (joined in this PR because they originated from the same issue and are very small): <br> - Materials scroll arrows appearing on desktop mode (fix with `width: 100%`); <br> - Fix smooth scrolling alignment in colors pickers (colors container has a transition-group, which adds a `span`, this had to be taken into account when implementing the `slideCentered` behaviour). <br><br> PR with the other fixes will be made in ripe-white (transparency in the scroll arrow buttons and smooth scrolling on colors)  |
| Animated GIF | Working: <br> ![scroll_colors](https://user-images.githubusercontent.com/25725586/105329986-afbec000-5bc9-11eb-863b-b203 …
=> #673: Fix colors scroll behaviour and materials arrows in desktop

vue/components/organisms/pickers/pickers.vue
| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/ripe-white/issues/673#issuecomment-765347573 |
| Decisions | The fix for the **point 3** (materials arrows not working in intermediate sizes) is https://github.com/ripe-tech/ripe-commons-pluginus/blob/0bb1202f0149919ec07370df1d2580ec5c41f645/vue/components/organisms/pickers/pickers.vue#L1254-L1258 <br> The change in https://github.com/ripe-tech/ripe-commons-pluginus/blob/0bb1202f0149919ec07370df1d2580ec5c41f645/vue/components/organisms/pickers/pickers.vue#L1247-L1251 is to make it similar to be `onColorsChanged`, since it may cause the same problem in the future. <br><hr><br> The **point 6** (center in select material and color if there was already one selected) is a new feature, which was implemented in …
=> #673: Polish picker scroll arrows

vue/components/atoms/button-platforme/button-platforme.stories.js, vue/components/atoms/button/button.stories.js, vue/components/atoms/icon/icon.stories.js, vue/components/atoms/image/image.stories.js, vue/components/atoms/loader/loader.stories.js, vue/components/molecules/keyboard/keyboard.stories.js, vue/components/molecules/thumbnails-groups/thumbnails-groups.stories.js
| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/ripe-twitch-ui/pull/74#issuecomment-771513137 <br> Fix to to pass the component title path in storiesOf() first argument and the story name in add() first argument. This fixes component search. Reference: https://github.com/storybookjs/storybook/blob/next/lib/core/docs/storiesOf.md#storiesof-api |
=> Fix storybook component search

vue/components/organisms/pickers/pickers.vue
| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/ripe-white/issues/673#issuecomment-776180527 |
| Decisions | - Resolved the problem in **point 6**, which was when the material stayed the same, the `activeMaterial` watcher was not triggered and the colors scroll didn't happen. <br> - Resolved **point 3**, where in some cases the scroll left and right were not working due to small differences in the `_sumElementsWidth` stop condition. The currently centered element was being chosen as the next one and the slide delta was 0. <br> - Also found another problem showcased in the GIFs below and it was fixed by removing a `scrollColors` call that was happening before the `parts` were updated. <br><br> @msp-platforme tested and gave the all clear regarding the 2 …
=> #673: Fix center same material

js/util/index.js, js/util/ripe.js, vue/components/organisms/personalization/personalization.vue, vue/mixins/logic.js, vue/store.js
| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/ripe-white/issues/641 |
| Decisions | Set legacy initials and engraving when `initials_extra` changes in `<personalization>` of ripe-commons-pluginus. The methodology is the same as in [ripe-sdk](https://github.com/ripe-tech/ripe-sdk/blob/088f6c6f4c6e0b8b4228088b67a6405cb0d9484a/src/js/base/ripe.js#L740). |
| Animated GIF | ![Peek 2020-11-12 11-39](https://user-images.githubusercontent.com/24736423/98936234-9835cd80-24dc-11eb-82d9-479615af16c0.gif) |
=> #641 Add fix for initials_extra event not updating initials and engraving

js/locale/locale.js, js/locale/model-locale-loader.js
| - | - |
| --- | --- |
| Issue | If we open a shoe with locale set to `en_us` then change that locale to `ja_jp` in white technical settings, the personlization modal will not update it's property options. See GIF below |
| Decisions | `locale_map_changed` needs to be triggered every time `localeMap` suffers mutations. Add triggers after calling `loadModelLocales` and  `loadRipeSdkLocales`.  |
=> Fix personalization modal properties locale reactivity

vue/components/organisms/configurator/configurator.vue
| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/ripe-white/issues/768  <br> When changing `options` prop, it has no effect in the configurator. |
| Decisions | Add watcher to options to update configurator options via `configurator.updateOptions`. |
=> #768 Fix configurator options reactivity

vue/components/organisms/pickers/pickers.vue
| - | - |
| --- | --- |
| Issue | Second issue in https://github.com/ripe-tech/ripe-white/issues/673#issuecomment-778146310 |
| Decisions |  Previous PR I had removed a piece of code that scrolled the colors after a material had been selected. This piece of code is necessary in retail since the transitions that happen in white do not happen in retail, not triggering the `onMaterialsChanged` function. <br> The function call was added but the conditional was fixed, so that only happens when `colorToggle` is `false`, which is what happens in retail (all colors appear instead of only the colors of the selected material). |
| Animated GIF | Now: <br> ![pickers-scroll-fix-retail](https://user-images.githubusercontent.com/25725586/108061315-05af4800-7050-11eb-90e8-91f779153d …
=> #673: scrollColors when colorToggle is false

js/base/main.js, vue/components/forms/personalization-form/reference.vue, vue/store.js
| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/ripe-white/issues/761 |
| Dependencies | https://github.com/ripe-tech/ripe-sdk/pull/247 |
| Decisions | Using hasInitialsRadius to control personalization image border radius as suggested by https://github.com/ripe-tech/ripe-white/issues/761#issuecomment-766660725  |
=> #761 Using hasInitialsRadius to control personalization image border radius

vue/components/forms/personalization-form/reference.vue
| - | - |
| --- | --- |
| Issue | After https://github.com/ripe-tech/ripe-commons-pluginus/pull/223 I, by mistake, added a computed `imageBorderRadius` value without removing data's `imageBorderRadius` value and merging the old logic to use `initialsImage.border_radius` in case it existed. |
| Decisions | This deletes duplicate data `imageBorderRadius` and uses old logic in the computed. |
=> #761 Fix duplicate borderRadius

js/base/main.js
| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/ripe-white/issues/768 <br> When doing `store.commit("ripeState", { someOption: false })` which will call `setRipeOptions({ someOption: false })` it will never set `someOption` to `false` as `options[key] && options[key] !== value` will always evaluate to `false` but it should be evaluating to `true`. <br> This also fixes the bug in which none of the boolean settings in Technical Settings > RIPE SDK are curretly working when they're set to false. |
| Decisions | Fix check before setting ripe options. |
=> #768 Fix setRipeOptions

js/base/main.js, package.json
| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/ripe-white/issues/768 |
| Decisions | Use yonius `_castR` to cast values in `_field` method as suggested in https://github.com/ripe-tech/ripe-white/pull/790#pullrequestreview-595457554 . This is to solve the problem that we're having in which is impossible to set a value to false using querystring because `Boolean("false")` and `Boolean("0")` will be translating to true. |
=> #768 Add yonius casting to _field method

js/base/main.js
| - | - |
| --- | --- |
| Issue | https://jenkins.platforme.com/job/ripe-tests/1768/ + new product ID number validation |
| Decisions | Related to https://github.com/ripe-tech/ripe-retail/pull/263. Important part is: `if (!isProductId) delete this.options.product_id;`. The rest is just moving that "option parsing" up before options are used.  |
=> fix: remove product ID from options

js/locale/model-locale-resolver.js, package.json
| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/ripe-twitch/issues/44 |
| Dependencies | https://github.com/ripe-tech/ripe-sdk/pull/252 |
| Decisions | Uses the newly implemented `localePart`, `localeMaterial`, `localeColor` and `localeProperty` methods of ripe-sdk to handle localization |
| Screenshot | **en_us:**<br>![imagem](https://user-images.githubusercontent.com/22588915/108517645-963f8f80-72bf-11eb-80eb-2320ebbdcbd3.png)<br><br>**pt_br:**<br>![imagem](https://user-images.githubusercontent.com/22588915/108517707-a8b9c900-72bf-11eb-89da-241d6e520829.png)<br><br>**Tests Passing:**<br>![imagem](https://user-images.githubusercontent.com/22588915/108517416-4bbe1300-72bf-11eb-835f-782e34a14327.png) |
=> #44 Using newly implemented ripe-sdk locale methods

js/base/main.js
| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/ripe-white/issues/825 <br> When [setModelConfig](https://github.com/ripe-tech/ripe-commons-pluginus/blob/master/js/base/main.js#L111) is called to set proper `$ripe.brand, $ripe.model, ...configs`, `ripe` will always be instantiated with a `null` variant. This is not intended. The fix is having `variant` in config coming from `this.options.variant`. This way, `ripe-white` which is already using and overriding `this.options` with a proper variant [here](https://github.com/ripe-tech/ripe-white/blob/master/js/plugins/base/main.js#L250), along with all the other options, will be able to set to the desired variant and later properly call `getPriceP` which otherwise would always have `null` variant.  |
| Dependencies | …
=> #845 Add missing variant to _buildConfig

CHANGELOG.md, vue/components/forms/personalization-form/reference.vue, vue/store.js
| - | - |
| --- | --- |
| Decisions | Triggered by https://github.com/ripe-tech/builds-static/pull/1207 |
=> fix: avoid calling 3DB logic methods with undefined ctx

CHANGELOG.md, vue/components/organisms/configurator/configurator.vue
| - | - |
| --- | --- |
| Dependencies | https://github.com/ripe-tech/ripe-sdk/pull/296 |
=> fix: set correct configurator size on init

CHANGELOG.md, vue/components/organisms/configurator/configurator.vue
| - | - |
| --- | --- |
| Issue | The configurator isn't properly reacting to the resolution set in SDK Options <img width="1865" alt="image" src="https://user-images.githubusercontent.com/24736423/141979265-7c7715b3-4072-4fcc-a1b3-70e3faa6c378.png">  or the one received in the URL params as it should. Repro URL: https://ripe-white-now.platforme.com/?brand=swear&model=vyner&locale=en_us&tech=1&resolution=100&p=lining%3Acalf_lining%3Awhite&p=front%3Anappa%3Awhite&p=side%3Anappa%3Awhite&p=sole%3Arubber%3Awhite&p=laces%3Anylon%3Awhite&p=logo%3Ametal%3Asilver&p=hardware%3Ametal%3Asilver&p=shadow%3Adefault%3Adefault |
| Decisions | Remove wrong size merge option introduced [here](https://github.com/ripe-tech/ripe-commons-pluginus/pull/264/files#diff-8d351241fd69fae9eceac110bf648712acf2a611b46d0 …
=> Resolution not being set

CHANGELOG.md, vue/components/forms/size-form/reference.vue, vue/components/organisms/size/size.vue
| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/ripe-white/issues/927 |
| Decisions | - Add `sizeLoaded` and use it as a callback to set the size state coming from the URL GET params |
=> #927 Gender, scale and size coming from URL params

CHANGELOG.md, vue/components/atoms/thumbnail/thumbnail.vue, vue/components/organisms/configurator/configurator.vue
| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/ripe-white/issues/943 |
| Dependencies | https://github.com/ripe-tech/ripe-sdk/pull/340 |
| Decisions | - Support rectangular thumbnails<br>- Support width and height resize in configurator |
**Test: use context `saint_laurent_hoodie`** 
https://user-images.githubusercontent.com/25725586/148554763-27ddc8f5-3e3d-4c3e-bc27-327445d1ad14.mp4
=> #943: Allow rectangular images in thumbnails and configurator

CHANGELOG.md, vue/components/forms/personalization-form/initials-images.vue
| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/ripe-white/issues/948 |
| Dependencies | Requires the removal of viewports in https://github.com/ripe-tech/builds-static/blob/bb0ef6bb197da9eae0e720abed371589b5578b09/config.static/saint_laurent/hoodie/spec.json#L333-L338|
| Decisions | - Support for width, height and frame in `initials-images`<br>- Send load event when all images of `initials-images` finish loading |
| Animated GIF | ![white-initials](https://user-images.githubusercontent.com/25725586/148993351-48f844e9-b1d2-4f8e-af3b-5622abb2ea73.gif)|
=> #948: initials image main rectangle

CHANGELOG.md, vue/components/forms/personalization-form/initials-images.vue
| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/ripe-white/issues/948 |
| Decisions | - Only sends loaded event if the image loaded is the same as the one we want to show. This is necessary because the frame might change while an update is being made in the previous frame and we do not want to show/load that. |
| Animated GIF |![white-improvements-initials](https://user-images.githubusercontent.com/25725586/149177498-dfc55bff-fe94-478f-ae4e-bd59d7112e33.gif) |
=> #948: Do not emit load:images event if frame is outdated

vue/components/forms/personalization-form/initials-images.vue
| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/ripe-sdk/pull/346 |
| Dependencies | |
| Decisions | Use pixel ratio in initials-images |
| Animated GIF | |
=> feat: use pixel ratio

CHANGELOG.md, vue/components/organisms/configurator/configurator.vue
| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/ripe-white/issues/954 |
| Decisions | - The initial dimensions of the configurator were not being passed, so it was defaulting to the 1000x1000 that are the default values of `width` and `height` of the configurator. If we removed that, it would default to the maximum width of the `.content` (1500px). It was necessary to pass this initials dimensions (which we already have calculated) so that they can be applied while the images load. |
| Animated GIF | ![white-scroll-bug fix](https://user-images.githubusercontent.com/25725586/149960340-5817a438-bbc4-4c67-aeb4-63a850edbabd.gif)![white-scroll-bug-fix-small](https://user-images.githubusercontent.com/25725586/149960382-db1893b5-4adf-4b72-9dd6-ce2d062f144e.gif …
=> #954: Set initial size, width and height of the configurator on bind

CHANGELOG.md, package.json
Necessary for testing https://github.com/ripe-tech/ripe-white/issues/954
* Set initial `size`, `width` and `height` on configurator bind so that the correct initial dimensions can be applied - [ripe-white/#954](https://github.com/ripe-tech/ripe-white/issues/954)
=> version: 0.20.2

CHANGELOG.md, vue/components/organisms/configurator/configurator.vue
| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/ripe-white/issues/962 |
| Decisions | - Only set flag `frameChanged` as `true` when there was a frame previously set, or else it will be `true` once the frame loads for the first time - it should show the drag indicator while that happens<br>- Add prop `showDragIndicator` that enables/disables the drag indicator. |
https://user-images.githubusercontent.com/25725586/153576523-9942724c-10fe-4e97-b589-ce999b2d870f.mp4
=> #962: Fix drag indicator in configurator

test/locale/model-locale-resolver.js, test/setup.js
| - | - |
| --- | --- |
| Issue | Revert node-fetch, related to https://github.com/ripe-tech/ripe-white/pull/969 |
| Dependencies |  |
| Decisions | - The problem was not in using node-fetch with the async import, it was in `self` not being populated with `fetch`. I browsed several repositories, I could not find any situation where something like this happened. I found a workaround, but I still don't know what dependency caused this. |
=> fix: revert to node-fetch 2 and added workaround

CHANGELOG.md, package.json, vue/store.js
| - | - |
| --- | --- |
| Issue | Bug found in retail, where it said it could not access store getter `getSizeState` |
| Dependencies | |
| Decisions | - `Size` component uses `getSizeState` getter from the store - https://github.com/ripe-tech/ripe-commons-pluginus/blob/545d77bd62ea14f6dc663522c46a2fd0ce79584e/vue/components/organisms/size/size.vue#L186 - however this getter is only available in the `RIPE White` store and not in the common store, which makes an error when running in `RIPE Retail`.<br><br>- Will require backport to `RIPE White`, since the getter will have to be removed from there |
=> feat: added getter `getSizeState` to the store

CHANGELOG.md, vue/components/forms/personalization-form/reference.vue
| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/ripe-white/issues/971  |
| Decisions | - Reacting to `$store.state.features` value for "open-externally" feature. |
=> #971 Features: reacting to open-externally for base plugins

CHANGELOG.md, vue/components/forms/personalization-form/initials-images.vue
| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/ripe-white/issues/978 |
| Decisions | - Added `minimumHeight` to `initials-images` so that it can be controlled instead of the default `600` - required for showing images bigger than 600px, which we want in the configurator container in white, while maitaining backward compatibility with existing plugins that make use of this, like emilio_pucci <br>- Support for undefined width and height for initials image's SDK `bindImage` - required since we want the resize of the image to be made by compose to maintain the correct aspect ratio. |
| Animated GIF | ![personalization-only-dummy](https://user-images.githubusercontent.com/25725586/157260535-2e448d4a-310f-4b1e-bb50-a5620bdc1ec0.gif)![personalization-only-ysl …
=> #978: Initials images minimum height and undefined width/height support

CHANGELOG.md, package.json
* Added `minHeight` to `initials-images` so that it can be controlled instead of the default `600` - [ripe-white/#978](https://github.com/ripe-tech/ripe-white/issues/978)
* Support for undefined width and height for initials image's SDK `bindImage` - [ripe-white/#978](https://github.com/ripe-tech/ripe-white/issues/978)
* Bumped dependencies
* Reacting to `open-externally` feature for base plugins - [ripe-white/#971](https://github.com/ripe-tech/ripe-white/issues/971)
=> version: 0.23.0

CHANGELOG.md, vue/components/forms/personalization-form/initials-images.vue
| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/ripe-white/issues/1005<br>![image](https://user-images.githubusercontent.com/25725586/159258667-ae49c23c-cc2a-4f57-ae4e-2ec2ef1e88d8.png) |
| Decisions | - Remove default value of `minWidth` for `initials-images`, in order to maintain the previous behaviour in initials-images used in personalization modal, which had a hardcoded height of `600px` and not set width. |
| Animated GIF | Now:<br>![image](https://user-images.githubusercontent.com/25725586/159258647-20bd75a9-d13d-47e4-ac81-75635ef24423.png)|
=> fix: remove default value of `minWidth` in initials-images

CHANGELOG.md, vue/components/atoms/thumbnail/thumbnail.vue, vue/components/molecules/thumbnails/thumbnails.vue, vue/components/organisms/configurator/configurator.vue
| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/ripe-white/issues/996 |
| Dependencies | https://github.com/ripe-tech/ripe-sdk/pull/377 |
| Decisions | - Show thumbnails that map to a video - the standard used was that frames that point to videohave the name `video-<video name>`.<br>- The video and thumbnails update when the customization change, since there might be no video for certain customizations.  |
https://user-images.githubusercontent.com/25725586/159502592-c9097962-8f4b-4efd-9388-129398494e2a.mp4
https://user-images.githubusercontent.com/25725586/159502626-bcfff4e5-2d40-4fac-91a9-e8970cf8ccfc.mp4
=> #996: Support for showing videos in White - thumbnails and configurator changes

CHANGELOG.md, vue/components/atoms/alert/alert.vue
| - | - |
| --- | --- |
| Issue | Alert text is not showing when clicking "Copy frame link" button of `link-technical` plugin. <br> Reproducible in [white now](https://ripe-white-now.platforme.com/?brand=swear&model=vyner). Found by @NFSS10   |
| Decisions | - Fix alert content by picking html or text. The previous implementation would always pick html, even if it was `undefined`. |
| Before | After |
| --- | --- |
| ![image](https://user-images.githubusercontent.com/24736423/197518887-80f8754d-c488-4cdd-a700-0a5594f51770.png) | ![image](https://user-images.githubusercontent.com/24736423/197518941-3704e674-9624-4594-be6d-1c6c6a4e95df.png) |
=> fix: alert content not showing text data

CHANGELOG.md, vue/components/organisms/pickers/pickers.vue
| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/ripe-white/issues/1078 |
| Decisions | * Add feature `show_restrictions` that will allow all restricted colors to still be displayed and clickable by default.<br>* Addicionally an `extraParameters=restrictions:disabled` can be received to change the behaviour to also display the restricted colors but not allow clicking. <br>* Previous behavior (not displaying restrited options) will remain unchanged when no feature is sent.|
| Animated GIFs |Unavailable (still clickable) ![](https://user-images.githubusercontent.com/10127604/200898393-896c4258-e6d8-4150-81c1-4e516c1f55ea.gif) Disabled (not clickable) ![](https://user-images.githubusercontent.com/10127604/200898391-5db8e9d2-7f92-4fb8-b533-58e99b108f7f.gif) |
=> #1078 Display restricted options

CHANGELOG.md, vue/components/atoms/thumbnail/thumbnail.vue, vue/components/organisms/configurator/configurator.vue
| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/ripe-white/issues/1013 |
| Decisions | - Change `onClick` event of `thumbnail` component to not trigger `show_frame` and delegate it, instead, to ripe-white's model-viewer <br> - Enhace `show_frame` event bind to also receive `options` as an argument |
=> #1013 Enhace `show_frame` with options and modify `thumbnail` component `onClick` action

CHANGELOG.md, package.json
* Add `show_restrictions` feature - [ripe-white/#1078](https://github.com/ripe-tech/ripe-white/issues/1078)
* Change `onClick` event of `thumbnail` component to not trigger `show_frame` and delegate it, instead, to ripe-white's model-viewer - [ripe-white/#1013](https://github.com/ripe-tech/ripe-white/issues/1013)
* Enhace `show_frame` event bind to also receive `options` as an argument  - [ripe-white/#1013](https://github.com/ripe-tech/ripe-white/issues/1013)
* Fix not showing alert content data text
=> chore: version 0.30.0 :rainbow: 

CHANGELOG.md, vue/components/organisms/pickers/pickers.vue
| - | - |
| --- | --- |
| Issue |https://github.com/ripe-tech/ripe-white/issues/1093 |
| Decisions | Small refactor on the logic used to display or hide the unavailable colors|
| Animated GIF | ![](https://user-images.githubusercontent.com/10127604/212401462-fe0b209b-9a2b-4f37-a3f0-45e633b3867f.gif)|
=> #1093 Unavailable colors being displayed

.github/workflows/deploy.yml, .github/workflows/main.yml, .travis.yml, CHANGELOG.md
| - | - |
| --- | --- |
| Issue | Builds are now failing because postcss [no loger supports node 12](https://github.com/postcss/postcss/blob/main/package.json#L6). Yarn actually informs of this and prevents the install but npm installer continues but later fails the build. Also, considering the current node LTS 18, we should consider updating versions. |
| Decisions | - Update node engine version of our github workflows  |
=> Bump CI/CD node engine versions

CHANGELOG.md, package.json
| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/ripe-sdk/issues/491 |
| Decisions | Update `ripe-sdk` version to `3.0.0` |
=> #493 Update `ripe-sdk` to version `3.0.0`
