vue/components/keyboard/keyboard.vue
vue/components/modal.vue
vue/components/personalization.vue
vue/components/personalization_form/initials_images.vue

Introduces some minor changes to make it the components responsive.

Improve UI for mobile devices

---

bundles/config.en_us.json
vue/components/personalization.vue

related to https://github.com/ripe-tech/ripe-white/issues/94

Personalization - clear initials #94

---

vue/components/pickers/pickers.vue

Before: https://recordit.co/lwmrOX3vdt
After: http://recordit.co/QeAsyrgZ34

Fix center color

---

vue/components/configurator.vue

perfect centering of loader

---

vue/components/personalization.vue
vue/components/pickers/pickers.vue
vue/components/size.vue

Fixed buttons afected by the changes in "button.css"

Buttons fix

---

vue/components/pickers/pickers.vue

Required by https://github.com/ripe-tech/ripe-white/pull/116 .

Add picker_part event

---

vue/components/pickers/pickers.vue

Add display none to hidden class

Fix hidden materials

---

vue/components/personalization.vue

Disable personalization button when the page is loading. Similar to the size component.

Disable personalization button when loading

---

js/base/main.js

Binding events for the undo and redo to work.

Added binds for the events needed for undo and redo

---

js/util/url_changer.js

| - | - |
| --- | --- |
| Issue | If URL had # encoded, information in the URL would be lost when reloading. |
| Decisions | Removed decodeURIComponent, which was decoding the # |

Fix URL # problem

---

js/base/main.js
vue/store.js

| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/ripe-white/issues/160 |
| Decisions | - |
| Animated GIF | - |

#160 Add hasCustomization state

---

vue/store.js

| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/ripe-white/issues/127 |
| Decisions | Store config format information in the store. Related to issue [#127](https://github.com/ripe-tech/ripe-white/issues/127). |

Store config format

---

vue/components/atoms/alert/alert.vue
vue/components/atoms/alert/index.js
vue/components/atoms/index.js
vue/components/index.js
vue/components/logic/global/global.vue
vue/components/logic/global/index.js
vue/components/logic/index.js
vue/mixins/utils.js

| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/ripe-white/issues/166 |
| Decisions | Global using Alert to be implemented in https://github.com/ripe-tech/ripe-white/pull/190 |
| Animated GIF | ![SITMomzdtx](https://user-images.githubusercontent.com/24736423/76754444-0d98a500-677a-11ea-8b62-5f8b39b6efdc.gif) |

#166 Add global alert

---

vue/mixins/logic.js

Used by https://github.com/ripe-tech/ripe-white/pull/221

Add logic methods for personalization text

---

vue/components/organisms/personalization/personalization.vue
vue/components/organisms/pickers/pickers.vue

| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/ripe-white/issues/169 |
| Decisions | Added support for extra custom pickers parts buttons |

#169 Allows to add extra buttons to pickers via slot

---

js/util/url-changer.js

| - | - |
| --- | --- |
| Decisions | Originated from the discussion in https://github.com/ripe-tech/ripe-white/issues/340#issuecomment-622127539 . |

Clear dku and product_id on URL change

---

vue/components/atoms/thumbnail/thumbnail.vue
vue/components/forms/personalization-form/initials-images.vue
vue/components/organisms/configurator/configurator.vue

| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/ripe-white/issues/341 |
| Dependencies | https://github.com/ripe-tech/ripe-sdk/pull/167 |
| Decisions | Awaiting `unbindImage` and `unbindConfigurator` |

#341 Await unbinds

---

.github/workflows/main.yml
.travis.yml
js/base/main.js
package.json
vue/store.js

| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/ripe-white/issues/441 |

#441: Copy all RIPE SDK config options

---

.github/workflows/main.yml
vue/test/base.js

Fix test $bus and add to Github workflow

---

vue/test/components/button/button.test.js

| - | - |
| --- | --- |
| Decisions | Fix test descriptions to be in accordance to conventions. |

Fix unit test description

---

js/base/main.js
js/locale/locale.js
vue/components/organisms/pickers/pickers.vue

| - | - |
| --- | --- |
| Issue | Related to https://github.com/ripe-tech/ripe-white/issues/427 |
| Decisions | Add event to fix locales reactivity in pickers - to be used in plugin.  |
| Animated GIF | - |

#427 Fix locales reactivity

---

vue/components/atoms/button/button.stories.js
vue/components/atoms/button/button.vue

| - | - |
| --- | --- |
| Animated GIF |  ![58kYts64uK](https://user-images.githubusercontent.com/8842023/86118931-7e659200-bac9-11ea-9ad9-d1fa89b26864.gif)|

Add disabled prop to button

---

vue/components/forms/size-form/reference-multi.vue
vue/components/forms/size-form/reference.vue

| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/ripe-white/issues/540 |
| Dependencies | https://github.com/ripe-tech/ripe-white/pull/552 |
| Decisions | Using the value of `store.genders` to filter the sizes show to the user  |
| Animated GIF | ![gender_parameter](https://user-images.githubusercontent.com/22588915/88900021-ba198600-d246-11ea-8246-71bde7f22733.gif)![gender_parameter_2](https://user-images.githubusercontent.com/22588915/88900026-bbe34980-d246-11ea-87ac-38e88dbef8a3.gif) |

#540 Filter genders sizes

---

js/base/main.js
js/util/url-changer.js
vue/store.js

| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/ripe-white/issues/561 |
| Decisions | Add URL theme sync to maintain UI theme state. |

#561 Sync theme with URL

---

vue/components/forms/personalization-form/initials-images.vue

| - | - |
| --- | --- |
| Decisions | After binding the images updates them, so that we the image URL is calculated. |
| Issue | https://github.com/ripe-tech/ripe-white/issues/531 |

Fix initials images groups watch

---

vue/components/forms/personalization-form/initials-images.vue

| - | - |
| --- | --- |
| Decisions | Add a loaded class for images to allow a more interesting UI. |
| Issue | https://github.com/ripe-tech/ripe-white/issues/531 |

Initials images loaded class

---

vue/components/forms/personalization-form/reference.vue

| - | - |
| --- | --- |
| Issue | Fixes https://github.com/ripe-tech/ripe-white/issues/562 |
| Decisions | Support missing initials properties. |

#562: Personalization support missing properties

---

package.json
vue/test/webpack.config.js

| - | - |
| --- | --- |
| Decisions | Backport https://github.com/ripe-tech/ripe-components-vue/pull/360 |

Add null loaders for tests

---

package.json
vue/test/setup.js
vue/test/webpack.config.js

| - | - |
| --- | --- |
| Dependencies | https://github.com/hivesolutions/pluginus/pull/5 |
| Decisions | Based on https://github.com/ripe-tech/ripe-components-vue/pull/372 |

New polyfill model

---

js/base/main.js
vue/components/molecules/thumbnails-groups/thumbnails-groups.vue
vue/mixins/logic.js
vue/store.js

| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/ripe-white/issues/531 https://github.com/ripe-tech/ripe-white/issues/532 |
| Decisions | Add common data and logic needed to work with initials, in order to save this logic being duplicated, making multiple requests for the same data, etc. |

Add initials capabilities to store and logicMixin

---

.storybook/addons.js
.storybook/main.js
.storybook/preview.js
package.json

| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/ripe-white/issues/600 |
| Dependencies | |
| Decisions | -- |

#600: Fix storybook deprecated configs

---

.github/PULL_REQUEST_TEMPLATE.md

| - | - |
| --- | --- |
| Issue | -- |
| Decisions | Fixed PR template |

Fixed pull request template

---

vue/components/forms/size-form/reference.vue

| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/ripe-white/issues/609 |
| Decisions | Fixed sizes genders not being translated |
| Animated GIF | ![fix](https://user-images.githubusercontent.com/22588915/95765007-25e98780-0ca9-11eb-9b8b-4427743255b0.gif) |

#609 Fixed sizes genders not being translated

---

package.json

| - | - |
| --- | --- |
| Issue | Related to https://github.com/ripe-tech/ripe-sdk/pull/205 |
| Decisions | Bump ripe-sdk version so that the personalization plugins work seamlessly with the new changes.  |

Bump ripe-sdk version

---

package.json

| - | - |
| --- | --- |
| Issue | `npm run test-watch:vue` is currently failing. |
| Decisions | Fix vue test watch script name.|

Fix test watch script

---

js/base/main.js

| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/ripe-white/issues/644 |
| Decisions | Add price_error bind to set null price and emit SDK message |

#644 Add price_error bind

---

vue/components/forms/personalization-form/reference.vue
vue/components/forms/size-form/reference.vue
vue/components/molecules/restrictions-alert/restrictions-alert.vue
vue/components/molecules/tabs/tab.vue
vue/components/organisms/configurator/configurator.vue
vue/components/organisms/personalization/personalization.vue
vue/components/organisms/size/size.vue
vue/mixins/utils.js
vue/plugins/locale.js
vue/test/mocks/mixins/index.js
vue/test/mocks/mixins/locale.js

| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/ripe-white/608 |
| Decisions | Add localized computed method to subscribe to locale store changes. This does the same as `locale` method but is reactive to `locale` changes in the store. |

#608 Add localized computed method to subscribe to locale store changes

---

bundles/config.en_us.json
bundles/config.ja_jp.json
bundles/config.zh_cn.json

| - | - |
| --- | --- |
| Issue | Fixes https://github.com/ripe-tech/ripe-white/issues/684 |

Fix locales for font size

---

vue/components/forms/personalization-form/reference.vue
vue/components/organisms/personalization/personalization.vue
vue/mixins/logic.js

| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/ripe-retail-vendors/issues/70 |
| Decisions | Add apply validation and pass it to slot. |
| Animated GIF |![bbbbbb](https://user-images.githubusercontent.com/24736423/98853592-44ca6d80-2451-11eb-8888-e4030f2c3d93.gif) |

#70 Personalization validation for apply button

---

vue/components/forms/personalization-form/reference.vue

| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/ripe-white/issues/688 |
| Decisions | Require all properties to be set. |
| Animated GIF | ![](http://g.recordit.co/sROWCUUvO2.gif) |

#688: Improve disable apply default condition

---

js/base/main.js
js/locale/model-locale-loader.js
package.json
vue/components/forms/size-form/reference.vue

| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/ripe-white/issues/685 |
| Dependencies | https://github.com/ripe-tech/ripe-sdk/pull/220 |
| Decisions | Adds bind of events before the SDK init to avoid concurrency problems. Add new bundle event to update `localePlugin` localeMap with new SDK locale bundles. |

#685 Add SDK locales to localePlugin's localeMap

---

js/base/main.js

Fix SDK init: use options

---

vue/components/forms/personalization-form/reference.vue
vue/mixins/logic.js

| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/ripe-retail-vendors/pull/82#discussion_r531658628 |

Refactor validation to allPropertiesOrEmpty

---

vue/components/forms/size-form/reference.vue
vue/components/organisms/size/size.vue

| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/ripe-white/issues/678 |
| Animated GIF | ![](http://g.recordit.co/sz8aoyQvqk.gif) |

Pick size when there is a single option

---

vue/components/organisms/size/size.vue

| - | - |
| --- | --- |
| Issue | Fixes https://github.com/ripe-tech/ripe-white/issues/691 |
| Animated GIF | ![](http://g.recordit.co/oLcGQV16O3.gif) |

#691: Fix size text locale

---

js/base/main.js
vue/mixins/logic.js

| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/ripe-white/issues/727 |
| Dependencies | https://github.com/ripe-tech/ripe-commons-pluginus/pull/203 |
| Decisions | Built on top of the DKU init fix so this specific fix could be tested. |

Fix DKU init initials extra

---

js/base/main.js
vue/mixins/logic.js

| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/ripe-white/issues/726 |
| Decisions | Fixes the loop but not the lack of initials. Will solve that in a different PR. |

Fix DKU init loop

---

vue/plugins/locale.js

| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/ripe-white/issues/756 |
Caused by https://github.com/ripe-tech/ripe-commons-pluginus/pull/209

fix: fix regression in locale fallback

---

vue/components/forms/personalization-form/initials-images.vue

| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/ripe-retail-vendors/issues/118 |

feat: add initials-images initialsBuilder watcher

---

js/locale/model-locale-resolver.js
package.json
test/locale/model-locale-resolver.js
test/setup.js
vue/components/organisms/pickers/pickers.vue
vue/plugins/locale.js

| - | - |
| --- | --- |
| Dependencies | https://github.com/ripe-tech/ripe-sdk/pull/240 |

feat: use SDK toLocaleModel

---

package.json

| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/ripe-white/issues/641#issuecomment-783317555 |

#641 Bump package - ripe-sdk version

---

js/base/main.js

| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/ripe-white/issues/768 |
| Dependencies | https://github.com/ripe-tech/ripe-sdk/pull/248 |
| Decisions | Add `size` to `ripeState` so we can mutate it after https://github.com/ripe-tech/ripe-sdk/pull/248 is merged  |

#768 Add size to ripeState

---

js/util/data.js
vue/mixins/utils.js

| - | - |
| --- | --- |
| Issue | Backport from https://github.com/ripe-tech/ripe-components-vue/pull/378 |

feat: backport buildSlug

---

vue/components/forms/size-form/reference.vue

| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/ripe-white/issues/801 |
| Decisions | We were working under the assumption that the genders would have the same available scales within the same model. This is not the case for N21 billy and removing that assumption will fix the issue. |
| Animated GIF |![](http://g.recordit.co/FZmo5OmHEc.gif)|

Fix: Removed the assumption that genders have the same scales

---

vue/components/forms/personalization-form/initials-images.vue

| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/ripe-retail-vendors/pull/135#discussion_r609619832 |

feat: Add height as prop

---

vue/components/forms/personalization-form/initials-images.vue

| - | - |
| --- | --- |
| Issue | ![image](https://user-images.githubusercontent.com/3048875/114569969-5799d600-9c6d-11eb-99b1-f7b84fb5d705.png) |

fix: initials images size regression

---

package.json

| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/ripe-white/issues/825 |

Bump versions: ripe-sdk

---

CHANGELOG.md
vue/store.js

| - | - |
| --- | --- |
| Issue | Caused by https://github.com/ripe-tech/ripe-commons-pluginus/pull/243 |

fix: size selection regression

---

.storybook/main.js
package.json

| - | - |
| --- | --- |
| Decisions | |
| Animated GIF | |

fix: storybook keeps reloading

---

CHANGELOG.md
vue/store.js

| - | - |
| --- | --- |
| Issue | Caused by #243 |

fix: missing size text on summary

---

package.json

| - | - |
| --- | --- |
| Issue | -- |
| Decisions | Bump ripe-sdk version to 2.0.1 |

feat: bump ripe-sdk version

---

CHANGELOG.md
vue/store.js

| - | - |
| --- | --- |
| Issue | Missing `u` in supported characters |
| Decisions | Added missing `u` |

Add missing "u"

---

js/base/main.js
vue/store.js

| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/ripe-white/issues/768 |
| Decisions | - Add usemasks definition to this store as requested [here](https://github.com/ripe-tech/ripe-white/pull/790#discussion_r660395189) |

#768 Add useMasks to store

---

CHANGELOG.md
vue/components/forms/personalization-form/initials-images.vue

| - | - |
| --- | --- |
| Decisions | Verified that no breaking changes happened on Swear / Sergio Rossi / generic plugin / retail. |
| Animated GIF | ![image](http://g.recordit.co/SVQNmiEam5.gif) |

feat: add open icon to initials

---

CHANGELOG.md
vue/components/forms/size-form/reference-multi.vue
vue/components/organisms/size/size.vue

| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/ripe-retail-vendors/issues/154 |

feat: override reference and available scales

---

CHANGELOG.md
vue/components/organisms/size/size.vue

| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/ripe-retail-vendors/issues/154 |
| Used By | https://github.com/ripe-tech/ripe-white/pull/897 |
| Animated GIF | ![](http://g.recordit.co/zjh1gCHbH1.gif) |

feat: flexible size modal select button label

---

CHANGELOG.md
vue/components/organisms/size/size.vue

| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/ripe-retail-vendors/issues/154 |
| Animated GIF | After: ![image](https://user-images.githubusercontent.com/3048875/131493471-6bde40c1-6ed1-4951-9ad7-d162b5dfceac.png)  <br/> Before: ![image](https://user-images.githubusercontent.com/3048875/131493581-6de3440c-e2e2-4591-a2c4-c2ac28b1e95b.png) |
| Related | https://github.com/ripe-tech/ripe-docs/pull/593 |

feat: get reference size and available scales from spec

---

CHANGELOG.md
vue/components/forms/size-form/reference.vue
vue/components/organisms/personalization/personalization.vue
vue/components/organisms/size/size.vue

| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/ripe-retail-vendors/issues/154 |
| Usage | https://github.com/ripe-tech/ripe-white/pull/900 |
| Animated GIF | ![](http://g.recordit.co/SIMCQA1hF7.gif) |

feat: configurable size and personalization labels

---

CHANGELOG.md
vue/components/organisms/configurator/configurator.vue

| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/ripe-sdk/issues/307 |
| Dependencies | https://github.com/ripe-tech/ripe-sdk/pull/313 |

fix: useMasks calculation for configurator

---

CHANGELOG.md
package.json

| - | - |
| --- | --- |
| Dependencies | https://github.com/ripe-tech/ripe-sdk/pull/315 |

version: 0.15.1

---

CHANGELOG.md
package.json

version: 0.16.1

---

CHANGELOG.md
package.json

| - | - |
| --- | --- |
| Issue | -- |
| Dependencies | --|
| Decisions | - Bump ripe-sdk and yonius - required to use initials builder for YSL |

feat: bump sdk and yonius

---

CHANGELOG.md
package.json

version: 0.20.3

---

package.json

| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/ripe-white/issues/993 |

feat: bump ripe-sdk version to 0.24.0

---

CHANGELOG.md
js/locale/dom-locale-loader.js
js/locale/file-locale-loader.js
js/locale/locale.js
js/locale/model-locale-loader.js
js/locale/model-locale-resolver.js
js/ui/base-personalization/base-personalization.js
js/ui/base-size/base-size.js
js/util/device.js
js/util/url-changer.js

| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/ripe-white/issues/1026 |
| Decisions | Add missing versions to all plugins. This is going to be used to get all technical plugin versions [here](https://github.com/ripe-tech/ripe-white/pull/1031/files#diff-0011c60ccfe7d6c1e67fe3d7f942c9da4554d930ac92c8d8383a1e3e7f8128feR270) |

#1026 Add versions to all plugins

---

CHANGELOG.md
vue/components/atoms/alert/alert.vue

| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/ripe-white/issues/1037 |
| Animated GIF | ![jsBTTtTAuD](https://user-images.githubusercontent.com/8842023/168635785-40573b52-ab9e-47a6-8987-dc7f0bf1790c.gif)|

feat: add html support to ´alert´ component

---

js/locale/locale.js
package.json

| - | - |
| --- | --- |
| Issue | No issue, no changelog. |
| Decisions | - Bump version of `pluginus`. <br> - Checking for locale value existence instead of store existence. |

fix: set store locale

---

CHANGELOG.md
package.json

* Bump packages
* Proper sync locale values between store locale and `this.locale` after coercing locale

version: 0.29.0

---

package.json

| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/ripe-white/issues/1089 |
| Decisions |- Remove temporary fix after https://github.com/ripe-tech/ripe-white/issues/1089 version `5.12.0` release |

chore: revert temp fix

---

CHANGELOG.md
package.json

* Bumped `ripe-sdk` package version
* Fix storybook build using non broken `enhanced-resolve` version - [#1089](https://github.com/ripe-tech/ripe-white/issues/1089)

version: 2.30.2

---

CHANGELOG.md
package.json

* Add `configuratorType` state variable and adapt configurator style to allow `CSR` type - [ripe-white/#1098](https://github.com/ripe-tech/ripe-white/issues/1098)
* Fix unavailable options being displayed - [ripe-white/#1093](https://github.com/ripe-tech/ripe-white/issues/1093)

 version 0.31.0 :rainbow: 

---

CHANGELOG.md
package.json
vue/components/organisms/configurator/configurator.vue

| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/ripe-sdk/issues/493 |
| Dependencies | https://github.com/ripe-tech/ripe-sdk/pull/494 |
| Decisions | - Improve CSR deinitialization process to allow CSR model swapping  |

#493 Improve CSR deinitialization in ripe-white

---

CHANGELOG.md
package.json

* Update ripe-sdk to `3.0.0` - [ripe-sdk/#491](https://github.com/ripe-tech/ripe-sdk/issues/491)

Version: `0.31.2`
